# Generated by Django 2.0.4 on 2018-05-12 21:10

from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings



class Migration(migrations.Migration):

    initial = True

    dependencies = [
#    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
#        migrations.CreateModel(
#            name='Profile',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
##                ('userID', models.CharField(max_length=50)),
##                ('userName', models.CharField(max_length=50)),
##                ('userPassword', models.CharField(max_length=50)),
#                ('userEmail', models.CharField(max_length=50)),
#                ('userFirstName', models.CharField(max_length=50)),
#                ('userLastName', models.CharField(max_length=50)),
#                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#
#            ],
#        ),

        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availQuarter', models.CharField(max_length=10)),
                ('availDelivery', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRSE_ID', models.IntegerField()),
                ('CRSE_TITLE', models.CharField(max_length=25)),
                ('CRSE_DESCRIPTION', models.CharField(max_length=250)),
                ('CRSE_SUBJECT', models.CharField(max_length=50)),
                ('CRSE_PREREQUISITE', models.CharField(max_length=250)),
                ('CRSE_NBR', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathQuarter', models.IntegerField()),
                ('pathSteps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRSE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_course_id', to='core.Courses')),
                ('PREREQUISITE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_id', to='core.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=50)),
                ('userEmail', models.CharField(max_length=50)),
                ('userFirstName', models.CharField(max_length=50)),
                ('userLastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_userID', to='core.Users'),
        ),
        migrations.AddField(
            model_name='path',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courseID', to='core.Courses'),
        ),
        migrations.AddField(
            model_name='availability',
            name='CRSE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_CRSE_ID', to='core.Courses'),
        ),
    ]
