# Generated by Django 2.0.5 on 2018-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180520_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CRSE_TITLE',
            field=models.TextField(),
        ),
    ]
